// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSSstatics
{
        public const string achievement_emergency_landing = "CgkI89bDw9MSEAIQAA"; // <GPGSID>
        public const string achievement_only_one_to_go = "CgkI89bDw9MSEAIQAw"; // <GPGSID>
        public const string achievement_twice = "CgkI89bDw9MSEAIQAg"; // <GPGSID>
        public const string achievement_power_overwhelming = "CgkI89bDw9MSEAIQBw"; // <GPGSID>
        public const string achievement_allpurposed = "CgkI89bDw9MSEAIQCA"; // <GPGSID>
        public const string achievement_repairing = "CgkI89bDw9MSEAIQAQ"; // <GPGSID>
        public const string achievement_little_boring = "CgkI89bDw9MSEAIQBQ"; // <GPGSID>
        public const string achievement_far_far_away = "CgkI89bDw9MSEAIQDQ"; // <GPGSID>
        public const string achievement_poison = "CgkI89bDw9MSEAIQCQ"; // <GPGSID>
        public const string achievement_ready_to_go_back_to_the_earth = "CgkI89bDw9MSEAIQBA"; // <GPGSID>
        public const string achievement_where_is_it_going = "CgkI89bDw9MSEAIQDA"; // <GPGSID>
        public const string achievement_why_is_this_here = "CgkI89bDw9MSEAIQBg"; // <GPGSID>
        public const string achievement_power_of_crystal = "CgkI89bDw9MSEAIQCw"; // <GPGSID>
        public const string achievement_artifacts = "CgkI89bDw9MSEAIQCg"; // <GPGSID>

}

